<a href="https://colab.research.google.com/github/vifirsanova/hse-python-course/blob/main/compression/pruning_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch, torch.nn as nn
from torch.nn.utils import prune

x = nn.Linear(4, 8) # линейный слой
x.weight # веса до прунинга

Parameter containing:
tensor([[-0.4985,  0.1800, -0.0991, -0.3820],
        [-0.2174,  0.3692, -0.4659,  0.3047],
        [ 0.1884,  0.3795, -0.0645,  0.3411],
        [-0.3326,  0.4300,  0.2608, -0.4334],
        [ 0.1554, -0.3963,  0.4014,  0.4443],
        [-0.2775,  0.1160,  0.0037, -0.1249],
        [ 0.0729,  0.1455, -0.0875, -0.4626],
        [-0.4964, -0.4620, -0.1111,  0.3576]], requires_grad=True)

**Прунинг** - это обнуление весов

`amount` - доля весов, подлежащих обнулению

Как мы ищем значения, которые ближе к 0?

- по пороговому значению
- с помощью регуляризации

Регуляризация используется для увеличения значений отрицательных весов и уменьшения значений положительных весов, чтобы найти вектор, который ближе к нулю, на основе расчета расстояния между векторами. Здесь, позволяет найти значения, близкие к нулю, и обнулить их.

`n` - значение `ord` для регуляризации:

```
sum(abs(x)**ord)**(1./ord)
```

`dim` - индекс (строки / столбцы)

In [8]:
y = prune.LnStructured(amount=0.5, n=1, dim=0)
y.prune(x.weight) # прунинг

tensor([[-0.0000,  0.0000, -0.0000, -0.0000],
        [-0.2174,  0.3692, -0.4659,  0.3047],
        [ 0.0000,  0.0000, -0.0000,  0.0000],
        [-0.3326,  0.4300,  0.2608, -0.4334],
        [ 0.1554, -0.3963,  0.4014,  0.4443],
        [-0.0000,  0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000, -0.0000, -0.0000],
        [-0.4964, -0.4620, -0.1111,  0.3576]], grad_fn=<MulBackward0>)

In [9]:
y = prune.LnStructured(amount=0.5, n=1, dim=1)
y.prune(x.weight) # прунинг

tensor([[-0.0000,  0.1800, -0.0000, -0.3820],
        [-0.0000,  0.3692, -0.0000,  0.3047],
        [ 0.0000,  0.3795, -0.0000,  0.3411],
        [-0.0000,  0.4300,  0.0000, -0.4334],
        [ 0.0000, -0.3963,  0.0000,  0.4443],
        [-0.0000,  0.1160,  0.0000, -0.1249],
        [ 0.0000,  0.1455, -0.0000, -0.4626],
        [-0.0000, -0.4620, -0.0000,  0.3576]], grad_fn=<MulBackward0>)

In [16]:
y = prune.LnStructured(amount=0.5, n=0, dim=1)
y.prune(x.weight) # прунинг

tensor([[-0.0000,  0.0000, -0.0991, -0.3820],
        [-0.0000,  0.0000, -0.4659,  0.3047],
        [ 0.0000,  0.0000, -0.0645,  0.3411],
        [-0.0000,  0.0000,  0.2608, -0.4334],
        [ 0.0000, -0.0000,  0.4014,  0.4443],
        [-0.0000,  0.0000,  0.0037, -0.1249],
        [ 0.0000,  0.0000, -0.0875, -0.4626],
        [-0.0000, -0.0000, -0.1111,  0.3576]], grad_fn=<MulBackward0>)