<a href="https://colab.research.google.com/github/vifirsanova/hse-python-course/blob/main/compression/quantization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

# матрица обученных весов
weight_matrix = np.array([
    [0.86, -1.88, -1.49, -0.51],
    [-1.7, 1.58, 0.12, -2.38],
    [1.9, -2.19, 1.37, -2.79],
    [1.92, 0.46, -2.85, -0.61]
])

# задаем центроиды (мы их посчитали заранее)
# значения будет подменять индексами массива (поэтому они расположены по возрастанию)
# -2.85 => 0
# -1.26 => 1
#  0.33 => 2
#  1.92 => 3
centroids = np.array([-2.85, -1.26, 0.33, 1.92])

# ищем ближайший центроид к каждому элементу матрицы весов
def assign_indices(weight_matrix, centroids):
    # 1. вычисляем разницу, чтобы найти ближайшие к центроидам значения:
    #    вычитаем значения центроидов из матриц весов
    diff = weight_matrix[:, :, None] - centroids
    for i in range(len(diff)):
        print('Centroid value:', centroids[i], '\nDifference matrix:\n', diff[i])
        print()
    # 2. ищем ближайшие значения:
    #    находим модули значений для каждой  difference matrix,
    #    чем ближе число к центроиду,
    #    тем ближе к 0 его модуль после вычитания центроида из матрицы
    abs_diff = np.abs(diff)
    for i in range(len(diff)):
        print('Centroid value:', centroids[i], '\nAbsolute difference matrix:\n', diff[i])
        print()
    # 3. заменяем вычисленные значения на индексы выявленных минимумов:
    #    argmin = 0 в absolute difference matrix
    indices = np.argmin(abs_diff, axis=2)
    return indices

# присваиваем новые индексы
indices_matrix = assign_indices(weight_matrix, centroids)

print("Weight matrix:")
print(weight_matrix)
print("\nCentroids:")
print(centroids)
print("\nIndices matrix (assigned centroid indices):")
print(indices_matrix)

Centroid value: -2.85 
Difference matrix:
 [[ 3.71  2.12  0.53 -1.06]
 [ 0.97 -0.62 -2.21 -3.8 ]
 [ 1.36 -0.23 -1.82 -3.41]
 [ 2.34  0.75 -0.84 -2.43]]

Centroid value: -1.26 
Difference matrix:
 [[ 1.15 -0.44 -2.03 -3.62]
 [ 4.43  2.84  1.25 -0.34]
 [ 2.97  1.38 -0.21 -1.8 ]
 [ 0.47 -1.12 -2.71 -4.3 ]]

Centroid value: 0.33 
Difference matrix:
 [[ 4.75  3.16  1.57 -0.02]
 [ 0.66 -0.93 -2.52 -4.11]
 [ 4.22  2.63  1.04 -0.55]
 [ 0.06 -1.53 -3.12 -4.71]]

Centroid value: 1.92 
Difference matrix:
 [[ 4.77  3.18  1.59  0.  ]
 [ 3.31  1.72  0.13 -1.46]
 [ 0.   -1.59 -3.18 -4.77]
 [ 2.24  0.65 -0.94 -2.53]]

Centroid value: -2.85 
Absolute difference matrix:
 [[ 3.71  2.12  0.53 -1.06]
 [ 0.97 -0.62 -2.21 -3.8 ]
 [ 1.36 -0.23 -1.82 -3.41]
 [ 2.34  0.75 -0.84 -2.43]]

Centroid value: -1.26 
Absolute difference matrix:
 [[ 1.15 -0.44 -2.03 -3.62]
 [ 4.43  2.84  1.25 -0.34]
 [ 2.97  1.38 -0.21 -1.8 ]
 [ 0.47 -1.12 -2.71 -4.3 ]]

Centroid value: 0.33 
Absolute difference matrix:
 [[ 4.75  3.16  